version: "3.8"
services:
  admin:
    build:
      context: admin
      target: ${TARGET:-production-pseudo}
    volumes:
      - .:/usr/app/dashboard

  nginx:
    build:
      context: docker/nginx
      target: ${TARGET:-production-pseudo}
    ports:
      - 8080:80
    volumes:
      - .:/usr/app/dashboard

  mysql:
    image: mysql:5.7.30
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: pass
    volumes:
      - mysql_data:/var/lib/mysql

  graphql:
    build: graphql
    ports:
      - 4000:4000
    volumes:
      - .:/usr/app/dashboard

volumes:
  mysql_data:
