version: "3.8"
services:
  admin:
    build:
      context: ./admin
      target: ${TARGET:-production-pseudo}
    volumes:
      - .:/usr/app/dashboard

  nginx:
    build:
      context: ./docker/nginx
      target: ${TARGET:-production-pseudo}
    ports:
      - 8080:80
    volumes:
      - .:/usr/app/dashboard

  mysql:
    image: mysql:5.7.30
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/contrib/initdb.d:/docker-entrypoint-initdb.d

  flyway:
    build:
      context: ./database
      target: ${TARGET:-production-pseudo}
    working_dir: /usr/app/dashboard/database
    volumes:
      - .:/usr/app/dashboard

  graphql:
    build: graphql
    ports:
      - 4000:4000
    volumes:
      - .:/usr/app/dashboard

volumes:
  mysql_data:
